### ISSUE TITLE
Error by $msgMon

### ISSUE THREAD

**Issue by freaknils** [KTamas/pflogsumm#5]
If I generate my statistics, I get the following error:

> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 2.
> Use of uninitialized value $msgMon in sprintf at /usr/bin/pflogsumm line 657, <> line 2.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 3.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 4.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 5.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 6.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 7.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 8.
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 9.
> ...
> Use of uninitialized value $msgMon in numeric gt (>) at /usr/bin/pflogsumm line 650, <> line 1077.

My perl version is
> perl -v
> 
> This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-thread-mult

How to fix?

**Comment by KTamas** [comment]
Hey, sorry, I had this up here as a personal for, I have not used it for years, so I am afraid I can not help you, sorry.
